# Generated by Django 5.2 on 2025-08-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_counted_view_post_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.TextField(null=True),
        ),
    ]
