# Generated by Django 5.2 on 2025-08-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_date']},
        ),
    ]
